---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    synced_folders: [
    ["/Users/mray/.vagrant.d/opt1204/chef", "/opt/chef"],
    ["/Users/mray/.vagrant.d/usr/local/bin", "/usr/local/bin"]
    ]
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    synced_folders: [
    ["/Users/mray/.vagrant.d/opt1004/chef", "/opt/chef"],
    ["/Users/mray/.vagrant.d/usr/local/bin", "/usr/local/bin"]
    ]
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: debian-7.1
  driver_config:
    synced_folders: [
    ["/Users/mray/.vagrant.d/opt71/chef", "/opt/chef"],
    ["/Users/mray/.vagrant.d/usr/local/bin", "/usr/local/bin"]
    ]
    box: opscode-debian-7.1
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-13.04
  driver_config:
    synced_folders: [
    ["/Users/mray/.vagrant.d/opt1304/chef", "/opt/chef"],
    ["/Users/mray/.vagrant.d/usr/local/bin", "/usr/local/bin"]
    ]
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test]
  attributes: {}

- name: cacher-client
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test::cacher-client]
  attributes: {}

- name: cacher-ng
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test::cacher-ng]
  attributes: {}

- name: cacher-ng-client
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test::cacher-ng-client]
  attributes:
    apt:
      cacher_dir: '/tmp/apt-cacher'
      cacher_port: '9876'
      cacher_interface: 'eth0'
      compiletime: true

- name: lwrps
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test::lwrps]
  attributes: {}
